# Generated by Django 5.0.2 on 2024-09-27 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flights', '0003_ticket'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='seat_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
